version: 0.0
os: linux

files:
  - source: Dockerfile
    destination: /home/ubuntu/my-flask-app/
  - source: app.py
    destination: /home/ubuntu/my-flask-app/
  - source: requirements.txt
    destination: /home/ubuntu/my-flask-app/
  - source: deploy.yml
    destination: /home/ubuntu/my-flask-app/
  - source: install_dependencies.sh
    destination: /home/ubuntu/scripts
  - source: start_docker_container.sh
    destination: /home/ubuntu/scripts
  - source: stop_docker_container.sh
    destination: /home/ubuntu/scripts
  - source: clean_up_existing_files.sh
    destination: /home/ubuntu/scripts

hooks:
  BeforeInstall:
    - location: clean_up_existing_files.sh
      timeout: 180
    - location: stop_docker_container.sh
      timeout: 180
  AfterInstall:
    - location: install_dependencies.sh
      timeout: 180
  ApplicationStart:
    - location: start_docker_container.sh
      timeout: 180
