version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-app .
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker tag my-app:latest 888577039597.dkr.ecr.eu-west-1.amazonaws.com/my-app-repo:latest
      - docker push 888577039597.dkr.ecr.eu-west-1.amazonaws.com/my-app-repo:latest
artifacts:
  files:
    - '**/*'
