version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-repository .
      - docker tag my-repository:latest <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/my-repository:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/my-repository:latest
