version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Use the updated AWS CLI v2 command for ECR login
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-repository .
      - docker tag my-repository:latest <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/my-repository:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/my-repository:latest
