version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Replace <aws_account_id> with your actual AWS account ID (850995537373)
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 850995537373.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-repository .
      - docker tag my-repository:latest 850995537373.dkr.ecr.us-east-1.amazonaws.com/my-repository:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 850995537373.dkr.ecr.us-east-1.amazonaws.com/my-repository:latest

