version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 850995537373.dkr.ecr.us-east-1.amazonaws.com
      - echo Logging in to Docker Hub...
      - docker login --username <your_docker_username> --password <your_docker_password>
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-repository .
      - docker tag my-repository:latest 850995537373.dkr.ecr.us-east-1.amazonaws.com/my-repository:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 850995537373.dkr.ecr.us-east-1.amazonaws.com/my-repository:latest
